#!/bin/sh
# This script may be used to run YCSB benchmarks for MongoDB on UNFS.
#
# Based on the specified device name, it will assume proper setup for running
# MongoDB on UNFS (using UNVMe driver or raw device) or on native filesystem.
#
# This test must be run from the mongo source directory.
# Output results will be saved to the "ycsb-results" directory.
#
# Run on UNFS using UNVMe driver:
#   $ unvme-setup
#   $ export UNFS_DEVICE 07:00.0
#   $ unfs-mongo-ycsb
#
# Run on UNFS using raw device:
#   $ unvme-setup reset
#   $ export UNFS_DEVICE /dev/nvme0n1
#   $ unfs-mongo-ycsb
#
# Run on native filesystem (assume XFS):
#   $ unvme-setup reset
#   $ unset UNFS_DEVICE
#   $ mkfs -t xfs /dev/nvme0n1
#   $ mount /dev/nvme0n1 /data
#   $ unfs-mongo-ycsb
#

# Default test options
: ${THREADS="1 8 16"}
: ${OPCOUNT=1000000}
: ${READS="95 50 5"}
: ${MONGODRV=mongodb}
#: ${MONGODRV=mongodb-async}

# Default test directories
: ${YCSB=/opt/ycsb/bin/ycsb}
: ${MONGOD=./mongod}
: ${DBPATH=/data/ycsb}
: ${LOGDIR=./ycsb-results}

# YCSB workload
YCSBTEXT="workload=com.yahoo.ycsb.workloads.CoreWorkload
recordcount=${OPCOUNT}
operationcount=${OPCOUNT}
readallfields=true
scanproportion=0
insertproportion=0
requestdistribution=zipfian"

if [ ! -x ${YCSB} ]; then echo "${YCSB} not found"; exit; fi
if [ ! -x ${MONGOD} ]; then echo "${MONGOD} not found"; exit; fi

# Program name and usage
PROG=$(basename $0)
USAGE="Usage: ${PROG} [DEVICE_NAME] [KEY=VALUE]..."

# Parsing test arguments
for i in $@; do
    case $i in
    [0-9A-Fa-f][0-9A-Fa-f]:[0-9A-Fa-f][0-9A-Fa-f].[0-9A-Fa-f])
        export UNFS_DEVICE=$i
        ;;

    /dev/*)
        export UNFS_DEVICE=$i
        ;;

    *=*)
        # Workload key=value may be specified to override defaults
        pattern=${i/=*/}
        if [[ "${YCSBTEXT}" =~ "${pattern}=" ]]; then
            YCSBTEXT=$(echo "${YCSBTEXT}" | sed "s/${pattern}=[_0-9A-Za-z]\+/$i/g")
        else
            YCSBTEXT="${YCSBTEXT}\n$i"
        fi
        ;;

    *)
        echo ${USAGE}
        exit 1
        ;;
    esac
done

case ${UNFS_DEVICE} in
[0-9A-Fa-f][0-9A-Fa-f]:[0-9A-Fa-f][0-9A-Fa-f].[0-9A-Fa-f])
    echo "Run YCSB on MongoDB with UNFS UNVMe Device ${UNFS_DEVICE}"
    CONFIG='--wiredTigerEngineConfigString extensions=[libunfswt.so={entry=unfs_wt_init,early_load=true}]'
    LOGSUFFIX="unvme.log"
    ;;
/dev/*)
    echo "Run YCSB on MongoDB with UNFS Raw Device ${UNFS_DEVICE}"
    CONFIG='--wiredTigerEngineConfigString extensions=[libunfswt.so={entry=unfs_wt_init,early_load=true}]'
    LOGSUFFIX="raw.log"
    ;;
*)
    echo "Run YCSB on MongoDB with Native Filesystem"
    LOGSUFFIX="xfs.log"
    ;;
esac

# Readjust OPCOUNT in case it was changed with specified parameter
OPCOUNT=$(echo ${YCSBTEXT} | sed 's/.*operationcount=\([0-9]\+\).*/\1/')

# Log directories
LOGPREFIX=${LOGDIR}/${HOSTNAME}
mkdir -p ${LOGDIR}

# Generate workload file
WORKLOAD=${LOGPREFIX}.${OPCOUNT}.workload
echo "${YCSBTEXT}" > ${WORKLOAD}
if [ $? -ne 0 ]; then exit; fi

prompt()
{
    #read -p "Press <Enter> to continue..."
    echo -e "\n========================"
    sleep 5
}

check_status()
{
    err=1
    for i in {1..30}; do
        sleep 5
        if [ -n "$(tail -10 $1 | grep "$2")" ]; then
            err=0
            break
        fi
        if [ -n "$(egrep -i 'Aborted:|aborting|terminating|BACKTRACE|Connection refused' $1)" ]; then
            sleep 5
            break
        fi
    done
    if [ ${err} -ne 0 ]; then
        tail -10 $1
        echo "ERROR: Expect: $2"
        exit 1
    fi
}

run_mongod()
{
    echo -e "\n${MONGODLOG}"
    rm -rf ${DBPATH}
    mkdir -p ${DBPATH}
    if [ -n "${UNFS_DEVICE}" ]; then
        export UNFS_DEVICE=${UNFS_DEVICE}
        unfs_format | tee -a ${MONGODLOG}
    fi

    cmd="numactl --interleave=all ${MONGOD} --quiet --dbpath ${DBPATH} ${CONFIG}"
    echo -e "\n=== ${cmd}" | tee -a ${MONGODLOG}
    ${cmd} >> ${MONGODLOG} 2>&1 &
    check_status ${MONGODLOG} 'waiting for connections'

    line=$(grep -n MongoDB ${MONGODLOG} | tail -1)
    tail -n +${line/:*/} ${MONGODLOG}
    prompt
}

load_ycsb()
{
    logfile=${LOGPREFIX}.${OPCOUNT}.t$1.load.${LOGSUFFIX}
    log9505=${LOGPREFIX}.${OPCOUNT}.t$1.r95w05.${LOGSUFFIX}
    log5050=${LOGPREFIX}.${OPCOUNT}.t$1.r50w50.${LOGSUFFIX}
    log0595=${LOGPREFIX}.${OPCOUNT}.t$1.r05w95.${LOGSUFFIX}

    # check if all tests have run successfully
    if [ -e ${logfile} ] && [ -n $(grep '[INSERT], Return=OK,' ${logfile}) ] && \
       [ -e ${log9505} ] && [ -n $(grep '[UPDATE], Return=OK,' ${log9505}) ] && \
       [ -e ${log5050} ] && [ -n $(grep '[UPDATE], Return=OK,' ${log5050}) ] && \
       [ -e ${log0595} ] && [ -n $(grep '[UPDATE], Return=OK,' ${log0595}) ]; then
        echo -e "\nSkip ${logfile}..."
    else
        echo -e "\n${logfile}"
        cmd="${YCSB} load ${MONGODRV} -P ${WORKLOAD} -threads $1"
        echo "=== ${cmd}" | tee ${logfile}
        echo "+++ $(date)" | tee -a ${logfile}
        ${cmd} 2>&1 | tee -a ${logfile}
        check_status ${logfile} 'Return=OK'
        echo "+++ $(date)" | tee -a ${logfile}
    fi
    prompt
}

run_ycsb()
{
    rp=$(printf '%02d' $2)
    wp=$(printf '%02d' $((100-$2)))
    logfile=${LOGPREFIX}.${OPCOUNT}.t$1.r${rp}w${wp}.${LOGSUFFIX}

    # check if test has run successfully
    if [ -e ${logfile} ] && [ -n $(grep '[UPDATE], Return=OK,' ${logfile}) ]; then
        echo -e "\nSkip ${logfile}..."
    else
        echo -e "\n${logfile}"
        cmd="${YCSB} run ${MONGODRV} -P ${WORKLOAD} -threads $1 -p readproportion=.${rp} -p updateproportion=.${wp}"
        echo "=== ${cmd}" | tee ${logfile}
        echo "+++ $(date)" | tee -a ${logfile}
        ${cmd} 2>&1 | tee -a ${logfile}
        check_status ${logfile} 'Return=OK'
        echo "+++ $(date)" | tee -a ${logfile}
    fi
    prompt
}

sudo sh -c "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
sudo sh -c "echo never > /sys/kernel/mm/transparent_hugepage/defrag"
killall -q mongod
sleep 2

for t in ${THREADS}; do
    MONGODLOG=${LOGPREFIX}.${OPCOUNT}.mongod.t$t.${LOGSUFFIX}
    rm -f ${MONGODLOG}
    run_mongod $t
    load_ycsb $t
    for r in ${READS}; do
        run_ycsb $t $r
    done
    killall mongod
    check_status ${MONGODLOG} 'shutting down with code:0'
    echo -e "============\n" >> ${MONGODLOG}
done


